coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "stellar-sdk/src/commonTest/**"
  - "stellar-sdk/src/jvmTest/**"
  - "stellar-sdk/src/jsTest/**"
  - "stellar-sdk/src/nativeTest/**"
  - "demo/**"
  - "docs/**"
