name: StellarDemo
options:
  bundleIdPrefix: com.soneso.stellar.demo
  deploymentTarget:
    iOS: 14.0
settings:
  base:
    ARCHS: arm64
    VALID_ARCHS: arm64
    EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
  ENABLE_USER_SCRIPT_SANDBOXING: NO
packages:
  swift-sodium:
    url: https://github.com/jedisct1/swift-sodium
    from: 0.9.1
targets:
  StellarDemo:
    type: application
    platform: iOS
    sources:
      - StellarDemo
    resources:
      - StellarDemo/Assets.xcassets
    info:
      path: StellarDemo/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: 1
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CADisableMinimumFrameDurationOnPhone: true
    settings:
      FRAMEWORK_SEARCH_PATHS:
        - $(inherited)
        - $(SRCROOT)/../../shared/build/bin/iosSimulatorArm64/debugFramework
        - $(SRCROOT)/../../shared/build/bin/iosArm64/debugFramework
      OTHER_LDFLAGS:
        - $(inherited)
        - -framework shared
    dependencies:
      - framework: ../shared/build/bin/iosSimulatorArm64/debugFramework/shared.framework
        embed: true
      - package: swift-sodium
        product: Clibsodium
    preBuildScripts:
      - script: |
          cd "$SRCROOT/../.."
          ./gradlew :demo:shared:linkDebugFrameworkIosSimulatorArm64
        name: Build Kotlin Framework
        basedOnDependencyAnalysis: false
      - script: |
          # Copy WASM resources from shared module to app bundle
          WASM_SOURCE_DIR="$SRCROOT/../shared/src/commonMain/resources/wasm"
          WASM_DEST_DIR="$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/wasm"

          if [ -d "$WASM_SOURCE_DIR" ]; then
            echo "Copying WASM resources from $WASM_SOURCE_DIR to $WASM_DEST_DIR"
            mkdir -p "$WASM_DEST_DIR"
            cp -v "$WASM_SOURCE_DIR"/*.wasm "$WASM_DEST_DIR/" || true
          else
            echo "Warning: WASM source directory not found at $WASM_SOURCE_DIR"
          fi
        name: Copy WASM Resources
        basedOnDependencyAnalysis: false
