// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecFunctionV0
 * {
 *     string doc<SC_SPEC_DOC_LIMIT>;
 *     SCSymbol name;
 *     SCSpecFunctionInputV0 inputs<>;
 *     SCSpecTypeDef outputs<1>;
 * };
 */
data class SCSpecFunctionV0Xdr(
  val doc: String,
  val name: SCSymbolXdr,
  val inputs: List<SCSpecFunctionInputV0Xdr>,
  val outputs: List<SCSpecTypeDefXdr>
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecFunctionV0Xdr {
      val doc = reader.readString()
      val name = SCSymbolXdr.decode(reader)
      val inputs = List(reader.readInt()) { SCSpecFunctionInputV0Xdr.decode(reader) }
      val outputs = List(reader.readInt()) { SCSpecTypeDefXdr.decode(reader) }
      return SCSpecFunctionV0Xdr(doc, name, inputs, outputs)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeString(doc)
    name.encode(writer)
    writer.writeInt(inputs.size)
    inputs.forEach { item ->
      item.encode(writer)
    }
    writer.writeInt(outputs.size)
    outputs.forEach { item ->
      item.encode(writer)
    }
  }
}
