// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecUDTUnionCaseTupleV0
 * {
 *     string doc<SC_SPEC_DOC_LIMIT>;
 *     string name<60>;
 *     SCSpecTypeDef type<>;
 * };
 */
data class SCSpecUDTUnionCaseTupleV0Xdr(
  val doc: String,
  val name: String,
  val type: List<SCSpecTypeDefXdr>
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecUDTUnionCaseTupleV0Xdr {
      val doc = reader.readString()
      val name = reader.readString()
      val type = List(reader.readInt()) { SCSpecTypeDefXdr.decode(reader) }
      return SCSpecUDTUnionCaseTupleV0Xdr(doc, name, type)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeString(doc)
    writer.writeString(name)
    writer.writeInt(type.size)
    type.forEach { item ->
      item.encode(writer)
    }
  }
}
