// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package com.soneso.stellar.sdk.xdr

/**
 * XDR Source:
 * struct SCSpecUDTStructV0
 * {
 *     string doc<SC_SPEC_DOC_LIMIT>;
 *     string lib<80>;
 *     string name<60>;
 *     SCSpecUDTStructFieldV0 fields<>;
 * };
 */
data class SCSpecUDTStructV0Xdr(
  val doc: String,
  val lib: String,
  val name: String,
  val fields: List<SCSpecUDTStructFieldV0Xdr>
) {
  companion object {

    fun decode(reader: XdrReader): SCSpecUDTStructV0Xdr {
      val doc = reader.readString()
      val lib = reader.readString()
      val name = reader.readString()
      val fields = List(reader.readInt()) { SCSpecUDTStructFieldV0Xdr.decode(reader) }
      return SCSpecUDTStructV0Xdr(doc, lib, name, fields)
    }
  }

  fun encode(writer: XdrWriter) {
    writer.writeString(doc)
    writer.writeString(lib)
    writer.writeString(name)
    writer.writeInt(fields.size)
    fields.forEach { item ->
      item.encode(writer)
    }
  }
}
