name: StellarDemo
options:
  bundleIdPrefix: com.soneso.stellar.demo
  deploymentTarget:
    macOS: 13.0
settings:
  ENABLE_USER_SCRIPT_SANDBOXING: NO
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
targets:
  StellarDemo:
    type: application
    platform: macOS
    sources:
      - StellarDemo
    info:
      path: StellarDemo/Info.plist
      properties:
        LSMinimumSystemVersion: "13.0"
        NSHumanReadableCopyright: Copyright © 2025 Stellar Development Foundation
    resources:
      - path: StellarDemo/Assets.xcassets
    settings:
      PRODUCT_NAME: "Stellar SDK Demo Native"  # Display name in Finder
      FRAMEWORK_SEARCH_PATHS:
        - $(inherited)
        - $(SRCROOT)/../../shared/build/bin/macosArm64/debugFramework
        - $(SRCROOT)/../../shared/build/bin/macosX64/debugFramework
      LIBRARY_SEARCH_PATHS:
        - $(inherited)
        - /opt/homebrew/opt/libsodium/lib
      HEADER_SEARCH_PATHS:
        - $(inherited)
        - /opt/homebrew/opt/libsodium/include
      OTHER_LDFLAGS:
        - $(inherited)
        - -L/opt/homebrew/opt/libsodium/lib
        - -lsodium
        - -framework shared
      MACOSX_DEPLOYMENT_TARGET: 13.0
    dependencies:
      - framework: ../shared/build/bin/macosArm64/debugFramework/shared.framework
        embed: true
    preBuildScripts:
      - script: |
          # Copy WASM resources from shared module to app bundle
          WASM_SOURCE_DIR="$SRCROOT/../shared/src/commonMain/resources/wasm"
          WASM_DEST_DIR="$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/Resources/wasm"

          if [ -d "$WASM_SOURCE_DIR" ]; then
            echo "Copying WASM resources from $WASM_SOURCE_DIR to $WASM_DEST_DIR"
            mkdir -p "$WASM_DEST_DIR"
            cp -v "$WASM_SOURCE_DIR"/*.wasm "$WASM_DEST_DIR/" || true
          else
            echo "Warning: WASM source directory not found at $WASM_SOURCE_DIR"
          fi
        name: Copy WASM Resources
        basedOnDependencyAnalysis: false
    #   - script: |
    #       cd "$SRCROOT/../../.."
    #       if [ "$(uname -m)" = "arm64" ]; then
    #         ./gradlew :demo:shared:linkDebugFrameworkMacosArm64
    #       else
    #         ./gradlew :demo:shared:linkDebugFrameworkMacosX64
    #       fi
    #     name: Build Kotlin Framework
    #     basedOnDependencyAnalysis: false
